version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-3"
    ECR_BACKEND_REPO: "ft_transcendence/backend"
    FRONTEND_S3_BUCKET: "transcendence-frontend-bucket" 
  exported-variables:
    - BACKEND_IMAGE_URI

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - BACKEND_IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND_REPO
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $BACKEND_IMAGE_URI
      - echo Backend Image URI $BACKEND_IMAGE_URI

  build:
    commands:
      - echo Building backend Docker image...
      - docker build -t $BACKEND_IMAGE_URI ./backend
      - docker tag $BACKEND_IMAGE_URI $BACKEND_IMAGE_URI:latest

  post_build:
    commands:
      - echo Pushing backend Docker image to ECR...
      - docker push $BACKEND_IMAGE_URI:latest

      - echo Deploying frontend to S3...
      - aws s3 sync ./frontend/site/ s3://$FRONTEND_S3_BUCKET/ --delete
      - echo Build and deployment complete!

artifacts:
  files: []
